"""AI agent RAG

Revision ID: 30208b23a2e7
Revises: a59e839f3cc4
Create Date: 2026-02-07 17:26:23.375722+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30208b23a2e7'
down_revision: Union[str, None] = 'a59e839f3cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_ip', sa.String(length=45), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_created_by_user_id'), 'knowledge_sources', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_is_deleted'), 'knowledge_sources', ['is_deleted'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=200), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_ip', sa.String(length=45), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_created_by_user_id'), 'knowledge_chunks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_is_deleted'), 'knowledge_chunks', ['is_deleted'], unique=False)
    op.create_table('agent_prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('goal_prompt', sa.Text(), nullable=True),
    sa.Column('instruction_prompt', sa.Text(), nullable=True),
    sa.Column('tool_prompt', sa.Text(), nullable=True),
    sa.Column('output_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_ip', sa.String(length=45), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_prompt_templates_created_by_user_id'), 'agent_prompt_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_agent_prompt_templates_is_deleted'), 'agent_prompt_templates', ['is_deleted'], unique=False)
    op.create_table('agent_rag_sources',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'source_id')
    )
    op.create_table('agent_runtime_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('task_prompt', sa.Text(), nullable=True),
    sa.Column('context_prompt', sa.Text(), nullable=True),
    sa.Column('memory_prompt', sa.Text(), nullable=True),
    sa.Column('scratchpad_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_ip', sa.String(length=45), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runtime_prompts_created_by_user_id'), 'agent_runtime_prompts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_prompts_is_deleted'), 'agent_runtime_prompts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_runtime_prompts_session_id'), 'agent_runtime_prompts', ['session_id'], unique=False)
    op.drop_index(op.f('ix_agent_api_keys_user_provider_id'), table_name='agent_api_keys')
    op.create_index(op.f('ix_agent_api_keys_provider_id'), 'agent_api_keys', ['provider_id'], unique=False)
    op.create_index('ix_agent_api_keys_user_provider', 'agent_api_keys', ['user_id', 'provider_id'], unique=False)
    op.create_unique_constraint('uq_agent_api_key', 'agent_api_keys', ['user_id', 'provider_id', 'label'])
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.add_column('custom_agents', sa.Column('memory_enabled', sa.Boolean(), nullable=False))
    op.add_column('custom_agents', sa.Column('memory_config', sa.JSON(), nullable=True))
    op.add_column('custom_agents', sa.Column('rag_enabled', sa.Boolean(), nullable=False))
    op.add_column('custom_agents', sa.Column('rag_config', sa.JSON(), nullable=True))
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('custom_agents', 'rag_config')
    op.drop_column('custom_agents', 'rag_enabled')
    op.drop_column('custom_agents', 'memory_config')
    op.drop_column('custom_agents', 'memory_enabled')
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-07 01:45:57.027517+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_constraint('uq_agent_api_key', 'agent_api_keys', type_='unique')
    op.drop_index('ix_agent_api_keys_user_provider', table_name='agent_api_keys')
    op.drop_index(op.f('ix_agent_api_keys_provider_id'), table_name='agent_api_keys')
    op.create_index(op.f('ix_agent_api_keys_user_provider_id'), 'agent_api_keys', ['user_id', 'provider_id'], unique=False)
    op.drop_index(op.f('ix_agent_runtime_prompts_session_id'), table_name='agent_runtime_prompts')
    op.drop_index(op.f('ix_agent_runtime_prompts_is_deleted'), table_name='agent_runtime_prompts')
    op.drop_index(op.f('ix_agent_runtime_prompts_created_by_user_id'), table_name='agent_runtime_prompts')
    op.drop_table('agent_runtime_prompts')
    op.drop_table('agent_rag_sources')
    op.drop_index(op.f('ix_agent_prompt_templates_is_deleted'), table_name='agent_prompt_templates')
    op.drop_index(op.f('ix_agent_prompt_templates_created_by_user_id'), table_name='agent_prompt_templates')
    op.drop_table('agent_prompt_templates')
    op.drop_index(op.f('ix_knowledge_chunks_is_deleted'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_created_by_user_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_sources_is_deleted'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_created_by_user_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
