"""rename metadata to extra_metadata in agent_chat_messages

Revision ID: 333d3dddde15
Revises: e7c2eeeb79e3
Create Date: 2026-02-10 12:44:46.435239+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '333d3dddde15'
down_revision: Union[str, None] = 'e7c2eeeb79e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['custom_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_conv_agent_user', 'agent_conversations', ['agent_id', 'user_id'], unique=False)
    op.create_index('ix_agent_conv_last_msg', 'agent_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_agent_conversations_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_id'), 'agent_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_is_deleted'), 'agent_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_conversations_thread_id'), 'agent_conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('agent_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('USER', 'AGENT', 'SYSTEM', name='agentchatsendertype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'PDF', name='agentchatmessagetype'), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_chat_messages_conversation_id'), 'agent_chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_messages_id'), 'agent_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_chat_messages_is_deleted'), 'agent_chat_messages', ['is_deleted'], unique=False)
    op.create_index('ix_agent_msg_conv_created', 'agent_chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_agent_msg_sender', 'agent_chat_messages', ['sender_type'], unique=False)
    op.create_table('agent_chat_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('is_rag_ingested', sa.Boolean(), nullable=False),
    sa.Column('rag_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['agent_chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rag_document_id'], ['rag_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_chat_files_conversation_id'), 'agent_chat_files', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_files_id'), 'agent_chat_files', ['id'], unique=False)
    op.create_index(op.f('ix_agent_chat_files_is_deleted'), 'agent_chat_files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_chat_files_message_id'), 'agent_chat_files', ['message_id'], unique=False)
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_models', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('custom_agents', 'action_mode_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_agents', 'autonomy_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='agentautonomylevel'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_agents', 'max_steps',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_agents', 'mcp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('llm_key_providers', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('llm_key_providers', 'is_system')
    op.alter_column('custom_agents', 'mcp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('custom_agents', 'max_steps',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('custom_agents', 'autonomy_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='agentautonomylevel'),
               server_default=sa.text("'low'::agentautonomylevel"),
               existing_nullable=False)
    op.alter_column('custom_agents', 'action_mode_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_models', 'api_key_prefix',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 14:01:31.988671+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_chat_files_message_id'), table_name='agent_chat_files')
    op.drop_index(op.f('ix_agent_chat_files_is_deleted'), table_name='agent_chat_files')
    op.drop_index(op.f('ix_agent_chat_files_id'), table_name='agent_chat_files')
    op.drop_index(op.f('ix_agent_chat_files_conversation_id'), table_name='agent_chat_files')
    op.drop_table('agent_chat_files')
    op.drop_index('ix_agent_msg_sender', table_name='agent_chat_messages')
    op.drop_index('ix_agent_msg_conv_created', table_name='agent_chat_messages')
    op.drop_index(op.f('ix_agent_chat_messages_is_deleted'), table_name='agent_chat_messages')
    op.drop_index(op.f('ix_agent_chat_messages_id'), table_name='agent_chat_messages')
    op.drop_index(op.f('ix_agent_chat_messages_conversation_id'), table_name='agent_chat_messages')
    op.drop_table('agent_chat_messages')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_thread_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_is_deleted'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agent_id'), table_name='agent_conversations')
    op.drop_index('ix_agent_conv_last_msg', table_name='agent_conversations')
    op.drop_index('ix_agent_conv_agent_user', table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###
