"""Refactor LLM models structure

Revision ID: 2eea265c8b6f
Revises: db58215d0632
Create Date: 2026-02-06 13:32:23.893267+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eea265c8b6f'
down_revision: Union[str, None] = 'db58215d0632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('agent_models', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_agent_models_provider'), table_name='agent_models')
    op.create_index(op.f('ix_agent_models_provider_id'), 'agent_models', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'agent_models', 'llm_key_providers', ['provider_id'], ['id'])
    op.drop_column('agent_models', 'provider')
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.drop_column('llm_key_providers', 'available_models')
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('llm_key_providers', sa.Column('available_models', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('agent_models', sa.Column('provider', postgresql.ENUM('openai', 'anthropic', 'google', 'gemini', 'ollama', 'huggingface', 'azure_openai', 'custom', 'groq', name='agentmodelprovider'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent_models', type_='foreignkey')
    op.drop_index(op.f('ix_agent_models_provider_id'), table_name='agent_models')
    op.create_index(op.f('ix_agent_models_provider'), 'agent_models', ['provider'], unique=False)
    op.drop_column('agent_models', 'provider_id')
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 18:02:40.849609+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
