"""Initial enterprise schema

Revision ID: 654f4e94c5fc
Revises: aa3bcd5bdea5
Create Date: 2026-02-05 08:06:26.260532+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '654f4e94c5fc'
down_revision: Union[str, None] = 'aa3bcd5bdea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 12:40:19.764441+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
