"""add_llm_provider_fields

Revision ID: 4c174dfda502
Revises: 3d710f3a3cba
Create Date: 2026-02-06 12:32:36.665792+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c174dfda502'
down_revision: Union[str, None] = '3d710f3a3cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.add_column('llm_api_keys', sa.Column('extra_params', sa.Text(), nullable=True))
    op.add_column('llm_key_providers', sa.Column('config_schema', sa.Text(), nullable=True))
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('llm_key_providers', 'config_schema')
    op.drop_column('llm_api_keys', 'extra_params')
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-06 13:51:41.285584+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
