"""add_purchase_and_doc_urls_to_llm_key_providers

Revision ID: 55f45aa2557f
Revises: ef9851773ef1
Create Date: 2026-02-10 17:02:06.325430+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55f45aa2557f'
down_revision: Union[str, None] = 'ef9851773ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('agent_executions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('agent_executions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('agent_executions', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('agent_executions', 'tokens_input',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_executions', 'tokens_output',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_executions', 'tokens_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_executions', 'duration_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_executions', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('agent_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_agent_exec_agent_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_exec_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_exec_user_id'), table_name='agent_executions')
    op.create_index(op.f('ix_agent_executions_agent_id'), 'agent_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_is_deleted'), 'agent_executions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_user_id'), 'agent_executions', ['user_id'], unique=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.add_column('llm_key_providers', sa.Column('purchase_url', sa.String(length=500), nullable=True))
    op.add_column('llm_key_providers', sa.Column('documentation_url', sa.String(length=500), nullable=True))
    op.alter_column('llm_key_providers', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('orchestrator_agents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('orchestrator_agents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orchestrator_agents', 'llm_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_agents', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'enable_long_term_memory',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'memory_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_agents', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_agents', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'enable_planning',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'enable_reasoning',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'can_stop_itself',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_orchestrator_agents_is_deleted'), 'orchestrator_agents', ['is_deleted'], unique=False)
    op.add_column('orchestrator_conversations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('orchestrator_conversations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orchestrator_conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_conversations', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('orchestrator_conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orchestrator_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orch_conv_agent_id'), table_name='orchestrator_conversations')
    op.drop_index(op.f('ix_orch_conv_thread_id'), table_name='orchestrator_conversations')
    op.drop_index(op.f('ix_orch_conv_user_id'), table_name='orchestrator_conversations')
    op.drop_constraint(op.f('orchestrator_conversations_thread_id_key'), 'orchestrator_conversations', type_='unique')
    op.create_index(op.f('ix_orchestrator_conversations_agent_id'), 'orchestrator_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_orchestrator_conversations_is_deleted'), 'orchestrator_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_orchestrator_conversations_thread_id'), 'orchestrator_conversations', ['thread_id'], unique=True)
    op.create_index(op.f('ix_orchestrator_conversations_user_id'), 'orchestrator_conversations', ['user_id'], unique=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_orchestrator_conversations_user_id'), table_name='orchestrator_conversations')
    op.drop_index(op.f('ix_orchestrator_conversations_thread_id'), table_name='orchestrator_conversations')
    op.drop_index(op.f('ix_orchestrator_conversations_is_deleted'), table_name='orchestrator_conversations')
    op.drop_index(op.f('ix_orchestrator_conversations_agent_id'), table_name='orchestrator_conversations')
    op.create_unique_constraint(op.f('orchestrator_conversations_thread_id_key'), 'orchestrator_conversations', ['thread_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orch_conv_user_id'), 'orchestrator_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_orch_conv_thread_id'), 'orchestrator_conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_orch_conv_agent_id'), 'orchestrator_conversations', ['agent_id'], unique=False)
    op.alter_column('orchestrator_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('orchestrator_conversations', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orchestrator_conversations', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('orchestrator_conversations', 'deleted_at')
    op.drop_column('orchestrator_conversations', 'is_deleted')
    op.drop_index(op.f('ix_orchestrator_agents_is_deleted'), table_name='orchestrator_agents')
    op.alter_column('orchestrator_agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orchestrator_agents', 'can_stop_itself',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'enable_reasoning',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'enable_planning',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orchestrator_agents', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orchestrator_agents', 'memory_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orchestrator_agents', 'enable_long_term_memory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'conversation'::character varying"),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'tools',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orchestrator_agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('4096'),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.7'::double precision"),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'gpt-4o'::character varying"),
               existing_nullable=False)
    op.alter_column('orchestrator_agents', 'llm_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'openai'::character varying"),
               existing_nullable=False)
    op.drop_column('orchestrator_agents', 'deleted_at')
    op.drop_column('orchestrator_agents', 'is_deleted')
    op.alter_column('llm_key_providers', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('llm_key_providers', 'documentation_url')
    op.drop_column('llm_key_providers', 'purchase_url')
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_executions_user_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_is_deleted'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_id'), table_name='agent_executions')
    op.create_index(op.f('ix_agent_exec_user_id'), 'agent_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_exec_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_exec_agent_id'), 'agent_executions', ['agent_id'], unique=False)
    op.alter_column('agent_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_executions', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('agent_executions', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('agent_executions', 'duration_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_executions', 'tokens_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_executions', 'tokens_output',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_executions', 'tokens_input',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_executions', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('agent_executions', 'deleted_at')
    op.drop_column('agent_executions', 'is_deleted')
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-10 22:28:08.250979+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
