"""Initial enterprise schema

Revision ID: a2cef8214637
Revises: local_models_002
Create Date: 2026-02-06 08:21:33.578219+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2cef8214637'
down_revision: Union[str, None] = 'local_models_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_api_keys', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('agent_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_api_keys', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_api_keys', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_api_keys', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_api_keys', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_api_keys_created_by_user_id'), 'agent_api_keys', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_agent_api_keys_is_deleted'), 'agent_api_keys', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('agent_api_keys_deleted_by_user_id_fkey'), 'agent_api_keys', type_='foreignkey')
    op.drop_column('agent_api_keys', 'deleted_by_user_id')
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('agent_connections', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('agent_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_connections', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_connections', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_connections', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_connections_created_by_user_id'), 'agent_connections', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_agent_connections_is_deleted'), 'agent_connections', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('agent_connections_deleted_by_user_id_fkey'), 'agent_connections', type_='foreignkey')
    op.drop_column('agent_connections', 'deleted_by_user_id')
    op.add_column('agent_mcp_servers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('agent_mcp_servers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('agent_mcp_servers', 'transport_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('agent_mcp_servers', 'requires_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_mcp_servers', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_mcp_servers', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_mcp_servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('agent_mcp_servers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_agent_mcp_servers_is_deleted'), 'agent_mcp_servers', ['is_deleted'], unique=False)
    op.add_column('agent_models', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('agent_models', 'requires_api_key',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'context_window',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_models', 'max_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_models', 'supports_vision',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'supports_tools',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'supports_streaming',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'input_price_per_million',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agent_models', 'output_price_per_million',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agent_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'is_deprecated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_models', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_models', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_models_created_by_user_id'), 'agent_models', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_agent_models_is_deleted'), 'agent_models', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('agent_models_deleted_by_user_id_fkey'), 'agent_models', type_='foreignkey')
    op.drop_column('agent_models', 'deleted_by_user_id')
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('agent_tools_config', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('agent_tools_config', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('agent_tools_config', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tools_config', 'requires_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tools_config', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tools_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('agent_tools_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_agent_tools_config_is_deleted'), 'agent_tools_config', ['is_deleted'], unique=False)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.add_column('custom_agents', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('custom_agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('custom_agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('custom_agents', 'frequency_penalty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('custom_agents', 'presence_penalty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('custom_agents', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'paused', 'archived', 'error', name='customagentstatus'),
               nullable=False)
    op.alter_column('custom_agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('custom_agents', 'total_sessions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'total_messages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('custom_agents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('custom_agents', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('custom_agents', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_custom_agents_created_by_user_id'), 'custom_agents', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_custom_agents_is_deleted'), 'custom_agents', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('custom_agents_deleted_by_user_id_fkey'), 'custom_agents', type_='foreignkey')
    op.drop_column('custom_agents', 'deleted_by_user_id')
    op.add_column('local_models', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('local_models', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('local_models', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('local_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('local_models', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('local_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('local_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('local_models', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_local_models_created_by_user_id'), 'local_models', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_local_models_is_deleted'), 'local_models', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('local_models_deleted_by_user_id_fkey'), 'local_models', type_='foreignkey')
    op.drop_column('local_models', 'deleted_by_user_id')
    op.add_column('model_download_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('model_download_logs', sa.Column('last_modified_ip', sa.String(length=45), nullable=True))
    op.alter_column('model_download_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_download_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_download_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_model_download_logs_created_by_user_id'), 'model_download_logs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_model_download_logs_is_deleted'), 'model_download_logs', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('model_download_logs_deleted_by_user_id_fkey'), 'model_download_logs', type_='foreignkey')
    op.drop_column('model_download_logs', 'deleted_by_user_id')
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=True)
    op.alter_column('users', 'account_type',
               existing_type=postgresql.ENUM('SUPERUSER', 'STAFF', 'CLIENT', name='accounttype'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=postgresql.ENUM('SUPERUSER', 'STAFF', 'CLIENT', name='accounttype'),
               server_default=sa.text("'STAFF'::accounttype"),
               existing_nullable=False)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('user_project_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('task_watchers', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('read_receipts', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('model_download_logs', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('model_download_logs_deleted_by_user_id_fkey'), 'model_download_logs', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_model_download_logs_is_deleted'), table_name='model_download_logs')
    op.drop_index(op.f('ix_model_download_logs_created_by_user_id'), table_name='model_download_logs')
    op.alter_column('model_download_logs', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('model_download_logs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_download_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('model_download_logs', 'last_modified_ip')
    op.drop_column('model_download_logs', 'is_deleted')
    op.add_column('local_models', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('local_models_deleted_by_user_id_fkey'), 'local_models', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_local_models_is_deleted'), table_name='local_models')
    op.drop_index(op.f('ix_local_models_created_by_user_id'), table_name='local_models')
    op.alter_column('local_models', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('local_models', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('local_models', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('local_models', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('local_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('local_models', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('local_models', 'last_modified_ip')
    op.drop_column('local_models', 'is_deleted')
    op.add_column('custom_agents', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('custom_agents_deleted_by_user_id_fkey'), 'custom_agents', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_custom_agents_is_deleted'), table_name='custom_agents')
    op.drop_index(op.f('ix_custom_agents_created_by_user_id'), table_name='custom_agents')
    op.alter_column('custom_agents', 'created_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_agents', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('custom_agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('custom_agents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_agents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_agents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_agents', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('custom_agents', 'total_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_agents', 'total_messages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_agents', 'total_sessions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_agents', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('custom_agents', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'paused', 'archived', 'error', name='customagentstatus'),
               nullable=True)
    op.alter_column('custom_agents', 'presence_penalty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('custom_agents', 'frequency_penalty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('custom_agents', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('custom_agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('custom_agents', 'last_modified_ip')
    op.alter_column('channel_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.alter_column('agent_tools_mapping', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_tools_config_is_deleted'), table_name='agent_tools_config')
    op.alter_column('agent_tools_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('agent_tools_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('agent_tools_config', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_tools_config', 'requires_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_tools_config', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('agent_tools_config', 'deleted_at')
    op.drop_column('agent_tools_config', 'is_deleted')
    op.alter_column('agent_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('agent_models', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_models_deleted_by_user_id_fkey'), 'agent_models', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_agent_models_is_deleted'), table_name='agent_models')
    op.drop_index(op.f('ix_agent_models_created_by_user_id'), table_name='agent_models')
    op.alter_column('agent_models', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_models', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_models', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_models', 'is_deprecated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'output_price_per_million',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agent_models', 'input_price_per_million',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agent_models', 'supports_streaming',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'supports_tools',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'supports_vision',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_models', 'max_output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_models', 'context_window',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_models', 'requires_api_key',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('agent_models', 'last_modified_ip')
    op.drop_index(op.f('ix_agent_mcp_servers_is_deleted'), table_name='agent_mcp_servers')
    op.alter_column('agent_mcp_servers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('agent_mcp_servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('agent_mcp_servers', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_mcp_servers', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_mcp_servers', 'requires_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_mcp_servers', 'transport_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('agent_mcp_servers', 'deleted_at')
    op.drop_column('agent_mcp_servers', 'is_deleted')
    op.add_column('agent_connections', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_connections_deleted_by_user_id_fkey'), 'agent_connections', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_agent_connections_is_deleted'), table_name='agent_connections')
    op.drop_index(op.f('ix_agent_connections_created_by_user_id'), table_name='agent_connections')
    op.alter_column('agent_connections', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_connections', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_connections', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_connections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_connections', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('agent_connections', 'last_modified_ip')
    op.alter_column('agent_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-02-05 15:55:01.270964+05:30'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('agent_api_keys', sa.Column('deleted_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_api_keys_deleted_by_user_id_fkey'), 'agent_api_keys', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_index(op.f('ix_agent_api_keys_is_deleted'), table_name='agent_api_keys')
    op.drop_index(op.f('ix_agent_api_keys_created_by_user_id'), table_name='agent_api_keys')
    op.alter_column('agent_api_keys', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_api_keys', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_api_keys', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_api_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_api_keys', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_api_keys', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('agent_api_keys', 'last_modified_ip')
    # ### end Alembic commands ###
